# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/configuration

version: 2

# Paths to exclude from scanning
paths-ignore:
  - "**/*.md"
  - "**/test_*.py"
  - "**/tests/**"
  - "**/.env.example"

# Specific secrets to ignore (false positives)
matches-ignore:
  - name: Attribution secret key (public by design)
    match: riturajprofile@162
  - name: Example API keys in documentation
    match: YOUR_.*_KEY_HERE

# Minimum entropy threshold for generic secrets (default is 3.0)
# Increase if getting too many false positives
minimum_entropy: 3.5
